config/routes.rb
Majordomo::Application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users

  resources :asset_logs, only: [:index]

  resources :assets do
    member do
      get :qrcode
      post :return
      post :borrow
    end
  end

  namespace :admin do
    root :to => 'assets#index'
    resources :assets do
      member do
        post :return
        post :borrow
      end
    end
  end
  
  match '/:id' => "shortener/shortened_urls#show"
  match '/assets/:uuid/borrowed_status' => "assets#borrowed_status"


  root :to => 'home#index'
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :borrower, polymorphic: true

  before_create :set_uuid

  validates :borrower, presence: true, if: -> { status == BORROWED }

  BORROWED = "borrowed"
  AVAILABLE = "available"

  def self.fetch_all_borrowed_by(borrower)
    where(borrower_id: borrower.id).
      where(borrower_type: borrower.class.name)
  end

  def set_uuid
    self.uuid = UUID.generate
  end

  def available?
    self.status == "available"
  end

  def borrow_for(borrower)
    self.borrower = borrower
    self.status = Asset::BORROWED
    self.save!
  end

  def return
    self.borrower = nil
    self.status = Asset::AVAILABLE
    self.save!
  end
end

app/controllers/admin/assets_controller.rb
class Admin::AssetsController < ApplicationController
  before_filter :authenticate_user!

  def index
    if current_user.admin?
      @assets = Asset.all
    else
      redirect_to assets_path
    end
  end

  def show
    @asset = Asset.find(params[:id])
    @asset_logs = AssetLog.fetch_all_for_asset(@asset)

    set_qrcode
  end

  def new
    @asset = Asset.new
  end

  def create
    AssetLog.logging_action_for current_user, params[:action] do |l|
      @asset = Asset.create(params[:asset])
      l.record_asset @asset

      redirect_to admin_asset_path(@asset)
    end
  end

  def edit
    @asset = Asset.find(params[:id])
  end

  def update
    @asset = Asset.find(params[:id])

    if params[:asset][:borrower_id]
      params[:asset][:status] = "borrowed"
      @asset.borrower = User.find(params[:asset][:borrower_id].to_i)
    else
      params[:asset][:status] = "available"
    end
    @asset.update_attributes(params[:asset])

    redirect_to admin_asset_path(@asset)
  end

  def qrcode
    @assets = {}
    params['label'].keys.each do |i|
      @assets[i] = Asset.find(params[:label][i])
    end

    render template: "assets/qrcode", layout: false
  end

  def borrowed_status
    @asset = Asset.find_by_uuid(params[:uuid])
  end

  def borrow
    AssetLog.logging_action_for current_user, params[:action] do |l|
      @asset = Asset.find(params[:id])
      l.record_asset @asset

      @asset.borrow_for(current_user)

      redirect_to admin_asset_path @asset
    end
  end

  def return
    AssetLog.logging_action_for current_user, params[:action] do |l|
      @asset = Asset.find(params[:id])
      l.record_asset @asset

      @asset.return

      redirect_to admin_asset_path @asset
    end
  end

  def set_qrcode
    url = view_context.borrow_asset_url(@asset)
    @qr = RQRCode::QRCode.new(url)
  end
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @assets = Asset.where("shared_resource = true")
  end

  def show
    @asset = Asset.find(params[:id])
    @asset_logs = AssetLog.fetch_all_for_asset(@asset)

    set_qrcode
  end

  def new
    @asset = Asset.new
  end

  def create
    AssetLog.logging_action_for current_user, params[:action] do |l|
      @asset = Asset.create(params[:asset])
      l.record_asset @asset

      redirect_to asset_path(@asset)
    end
  end

  def edit
    @asset = Asset.find(params[:id])
  end

  def update
    @asset = Asset.find(params[:id])

    @asset.update_attributes(params[:asset])

    redirect_to asset_path(@asset)
  end

  def qrcode
    @assets = {}
    params['label'].keys.each do |i|
      @assets[i] = Asset.find(params[:label][i])
    end

    render template: "assets/qrcode", layout: false
  end

  def borrowed_status
    @asset = Asset.find_by_uuid(params[:uuid])
  end

  def borrow
    AssetLog.logging_action_for current_user, params[:action] do |l|
      @asset = Asset.find(params[:id])
      l.record_asset @asset

      @asset.borrow_for(current_user)

      BorrowedAssetNotifier.notify_borrowed_asset(current_user, @asset).deliver
      
      redirect_to asset_path @asset
    end
  end

  def return
    AssetLog.logging_action_for current_user, params[:action] do |l|
      @asset = Asset.find(params[:id])
      l.record_asset @asset

      @asset.return

      redirect_to asset_path @asset
    end
  end

  def set_qrcode
    url = view_context.borrow_asset_url(@asset)
    @qr = RQRCode::QRCode.new(url)
  end
end

app/helpers/admin/assets_helper.rb
module Admin::AssetsHelper

  def user_choices
    choices = [["--", nil]]
    user_choices = User.all.map {|u| [u.name, u.id]}
    choices + user_choices
  end
end

app/helpers/assets_helper.rb
module AssetsHelper
  def borrow_asset_url(asset)
    short_url([assets_url, asset.uuid, "borrowed_status"].join('/'))
  end
end

app/views/admin/assets/edit.html.erb
<br/>
<section class="row">

<div class="large-6 columns">

<%= form_for @asset, :url => admin_asset_path(@asset) do %>
  <%= render partial: "assets/fields" %>

  <label>
  Is assigned to:
  <%= select_tag "asset[borrower_id]", options_for_select(user_choices, user_choices.first) %>
  </label>

  <input type="submit" value="Save!" class="a-button"/>
  <%= link_to "Cancel", admin_asset_path(@asset), :class => "a-button" %>
<% end %>

</div>

</section>

app/views/admin/assets/index.html.erb
<% content_for :styles do %>
<%= stylesheet_link_tag "crud" %>
<% end %>


<section class="row">
<div class="large-12 columns ">
  <%= link_to "New Asset", new_asset_path(@asset), :class => "a-button createButton" %>
</div>
<div class="large-12 columns">
	<h1>All Assets</h1>
</div>

<div class="large-12 columns">
	<table width="100%">
  <thead>
    <th>
      &nbsp;
    </th>
    <th width="30%">
      Name
    </th>
    <th width="15%">
      Status
    </th>
    <th width="15%">
      Shared?
    </th>
    <th width="20%">
      Borrower
    </th>
    <th width="20%">
      Modified
    </th>
  </thead>

  <tbody>
  <% @assets.each do |asset| %>
    <tr class='asset-row' data-asset-name='<%= asset.name %>'>
      <td>
        <input name="print_asset_tag" type="checkbox" value="<%= asset.id %>" class="print-asset-tag-checkbox" />
      </td>
      <td>
        <%= link_to asset.name, admin_asset_path(asset) %>
      </td>
      <td>
        <%= asset.status %>
      </td>
      <td>
        <%= asset.shared_resource? %>
      </td>
      <td> 
        <% if asset.borrower %>
          <%= link_to asset.borrower.name, user_path(asset.borrower)  %>
        <% end %>
      </td>
      <td>
        <%= asset.updated_at %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<a href="#" class="a-button print-selected-tags">
  Print ID tags for selected assets
</a> 


</div>
</section>

<div id="printTagModal" class="reveal-modal large">
  <h2>Print Options</h2>
  <p class="lead">Select the areas on the sheet on which to print the labels.</p>

  <div class="gridster" style="width: 500px; height: 500px;">
    <ul>
      <li data-row="1" data-col="1" data-sizex="2" data-sizey="1" class="asset-tag-1"></li>
      <li data-row="2" data-col="1" data-sizex="2" data-sizey="1" class="asset-tag-3"></li>
      <li data-row="3" data-col="1" data-sizex="2" data-sizey="1" class="asset-tag-5"></li>
      <li data-row="4" data-col="1" data-sizex="2" data-sizey="1" class="asset-tag-7"></li>
      <li data-row="5" data-col="1" data-sizex="2" data-sizey="1" class="asset-tag-8"></li>

      <li data-row="1" data-col="2" data-sizex="2" data-sizey="1" class="asset-tag-2"></li>
      <li data-row="2" data-col="2" data-sizex="2" data-sizey="1" class="asset-tag-4"></li>
      <li data-row="3" data-col="2" data-sizex="2" data-sizey="1" class="asset-tag-6"></li>
      <li data-row="4" data-col="2" data-sizex="2" data-sizey="1" class="asset-tag-8"></li>
      <li data-row="5" data-col="2" data-sizex="2" data-sizey="1" class="asset-tag-10"></li>
    </ul>
  </div>

  <a href="#" class="button print-tags">
    Print
  </a>

  <a class="close-reveal-modal">&#215;</a>
</div>

<%= stylesheet_link_tag 'jquery.gridster' %>

app/views/admin/assets/show.html.erb
<% content_for :styles do %>
<%= stylesheet_link_tag "crud" %>
<% end %>


<section class="row">

<div class="large-12 colums">

<h1><%= @asset.name %></h1>



<div class="row">
<section class="large-6 columns">
  
  <% if @asset.borrower == current_user %>
    <form action="<%= return_admin_asset_path(@asset) %>" method="POST">
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>"/>
      <input type="submit" value="Return!" class="a-button" />
    </form>
    <span class="label-value">Status:</span>
    <p class="value">Borrowed by you</p>
    
  <% elsif @asset.available? %>
    <form action="<%= borrow_admin_asset_path(@asset) %>" method="POST">
        <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>"/>
      <input type="submit" value="Borrow!" class="a-button" />
    </form>
    <span class="label-value">Status:</span>
    <p class="value">Available</p>
  <% else %>
    <p class="value">Borrowed by <%= @asset.borrower.name %></p>
    <form action="<%= return_admin_asset_path(@asset) %>" method="POST">
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>"/>
      <input type="submit" value="Unassign!" class="a-button" />
    </form>
  <% end %>

  <span class="label-value">Shared resource:</span>
  <p class="value"><%= @asset.shared_resource? %></p>

  <span class="label-value">Description:</span>
  <p class="value"><%= @asset.description %></p>

  <span class="label-value">Notes:</span>
  <p class="value"><%= @asset.notes %></p>

  <span class="label-value">UUID:</span>
  <p class="value"><%= @asset.uuid %></p>
  
  <a href="#" class="a-button marginRight" data-reveal-id="printTagModal">
    Print QR Code Tag
  </a> 
  <%= link_to "Edit", edit_admin_asset_path(@asset), :class =>"a-button" %>

</section>


<section class="large-6 columns paperTrail">
  <div class="paperTrail-title">
    <h2>Asset History</h2>
  </div>
  <div class="paperTrail-content">
    <%= render partial: "asset_logs/asset_logs_list", locals: { asset_logs: @asset_logs } %>
  </div>
</section>

</div>



</div>

</section>

<div id="printTagModal" class="reveal-modal medium">
  <h2>Print Options</h2>
  <p class="lead">Select the area on the sheet on which to print the label.</p>
  
  <table>
    <tr>
      <td width="80">
        <%= link_to "Label 1", qrcode_asset_path(@asset, format: 'pdf', 'label[1]' => @asset.id), target: '_blank' %>
      </td>
      <td width="80">
        <%= link_to "Label 2", qrcode_asset_path(@asset, format: 'pdf', 'label[2]' => @asset.id), target: '_blank'  %>
      </td>
    </tr>
    <tr>
      <td>
        <%= link_to "Label 3", qrcode_asset_path(@asset, format: 'pdf', 'label[3]' => @asset.id), target: '_blank'  %>
      </td>
      <td>
        <%= link_to "Label 4", qrcode_asset_path(@asset, format: 'pdf', 'label[4]' => @asset.id), target: '_blank'  %>
      </td>
    </tr>
    <tr>
      <td>
        <%= link_to "Label 5", qrcode_asset_path(@asset, format: 'pdf', 'label[5]' => @asset.id), target: '_blank'  %>
      </td>
      <td>
        <%= link_to "Label 6", qrcode_asset_path(@asset, format: 'pdf', 'label[6]' => @asset.id), target: '_blank'  %>
      </td>
    </tr>
    <tr>
      <td>
        <%= link_to "Label 7", qrcode_asset_path(@asset, format: 'pdf', 'label[7]' => @asset.id), target: '_blank'  %>
      </td>
      <td>
        <%= link_to "Label 8", qrcode_asset_path(@asset, format: 'pdf', 'label[8]' => @asset.id), target: '_blank'  %>
      </td>
    </tr>
    <tr>
      <td>
        <%= link_to "Label 9", qrcode_asset_path(@asset, format: 'pdf', 'label[9]' => @asset.id), target: '_blank'  %>
      </td>
      <td>
        <%= link_to "Label 10", qrcode_asset_path(@asset, format: 'pdf', 'label[10]' => @asset.id), target: '_blank'  %>
      </td>
    </tr>
  </table>
  <a class="close-reveal-modal">&#215;</a>
</div>