config/routes.rb
Majordomo::Application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users

  resources :asset_logs, only: [:index]

  resources :assets do
    member do
      get :qrcode
      post :return
      post :borrow
    end
  end

  namespace :admin do
    root :to => 'assets#index'
    resources :assets do
      member do
        post :return
        post :borrow
      end
    end
  end
  
  match '/:id' => "shortener/shortened_urls#show"
  match '/assets/:uuid/borrowed_status' => "assets#borrowed_status"


  root :to => 'home#index'
end

app/views/shared/_metadata.html.erb
<title><%= content_for?(:title) ? yield(:title) : "Majordomo - Asset Tracking" %></title>
<meta charset="utf-8" />
<!-- Uncomment to make IE8 render like IE7 -->
<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
<!-- Set the viewport width to device width for mobile -->
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<%= csrf_meta_tags %>

app/views/shared/_nav-home.html.erb
<div class="navigation_wrapper">

<section class="row">

<div class="small-6 large-8 columns">
	<h1 class="logo">Majordomo</h1>
</div> 

<nav class="small-6 large-4 columns">
 <%= link_to "Sign in", user_omniauth_authorize_url(provider: "google"), :class => "a-button" %>

</nav>

</section>

</div>

app/views/shared/_navigation-app.html.erb
<div class="navigation_wrapper">

<section class="row">

<div class="primary-nav small-6 large-2 columns">
	<a href="/"><h1 class="logo">Majordomo</h1></a>

</div> 

<nav class="small-12 large-10 columns">
 <%= link_to "Find Assets", assets_path, :class => "small-button" %> 
  <% if current_user.admin? %>
    <%= link_to "Manage Assets", admin_root_path, :class => "small-button" %> 
    <%= link_to "Asset Log", asset_logs_path, :class => "small-button" %> 
    <%= link_to "Users", users_path, :class => "small-button" %> 
  <% else %>
    <%= link_to "My Assets", user_path(current_user), :class => "small-button" %> 
  <% end %>
 <%= link_to "Sign out", destroy_user_session_url, method: :delete, :class => "a-button" %>


</nav>

</section>

</div>

app/views/shared/_navigation.html.erb
<nav class="top-bar">

<div class="row">
  <section class="large-12">

  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1 class="main-logo">
      <%= link_to "Majordomo", root_url %>
      </h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->

    <% if user_signed_in? -%>
    <ul class="left">
      <li class="nav-link active"><%= link_to "View tracked Assets", assets_path %></li>
      <li class="nav-link"><%= link_to "+ Create new Asset", new_asset_path(@asset) %></li>

    </ul>
    <% end %>

    <!-- Right Nav Section -->
    <ul class="right">

     <li class="has-form nav-link">
       <% if user_signed_in? -%>
         <%= link_to "Sign out", destroy_user_session_url, method: :delete %>
       <% else -%>
         <%= link_to "Sign in", user_omniauth_authorize_url(provider: "google") %>
       <% end -%>
     </li>

    </ul>
  </section>

  </section>

  </div>

</nav>

app/views/shared/_stylesheet.html.erb
<!--Base styles-->
<%= stylesheet_link_tag "application", "basement", "forms" %>

<!--Page specific styles-->
<%= yield :styles %>