config/routes.rb
Majordomo::Application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users

  resources :asset_logs, only: [:index]

  resources :assets do
    member do
      get :qrcode
      post :return
      post :borrow
    end
  end

  namespace :admin do
    root :to => 'assets#index'
    resources :assets do
      member do
        post :return
        post :borrow
      end
    end
  end
  
  match '/:id' => "shortener/shortened_urls#show"
  match '/assets/:uuid/borrowed_status' => "assets#borrowed_status"


  root :to => 'home#index'
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :borrower, polymorphic: true

  before_create :set_uuid

  validates :borrower, presence: true, if: -> { status == BORROWED }

  BORROWED = "borrowed"
  AVAILABLE = "available"

  def self.fetch_all_borrowed_by(borrower)
    where(borrower_id: borrower.id).
      where(borrower_type: borrower.class.name)
  end

  def set_uuid
    self.uuid = UUID.generate
  end

  def available?
    self.status == "available"
  end

  def borrow_for(borrower)
    self.borrower = borrower
    self.status = Asset::BORROWED
    self.save!
  end

  def return
    self.borrower = nil
    self.status = Asset::AVAILABLE
    self.save!
  end
end

app/controllers/admin/assets_controller.rb
class Admin::AssetsController < ApplicationController
  before_filter :authenticate_user!

  def index
    if current_user.admin?
      @assets = Asset.all
    else
      redirect_to assets_path
    end
  end

  def show
    @asset = Asset.find(params[:id])
    @asset_logs = AssetLog.fetch_all_for_asset(@asset)

    set_qrcode
  end

  def new
    @asset = Asset.new
  end

  def create
    AssetLog.logging_action_for current_user, params[:action] do |l|
      @asset = Asset.create(params[:asset])
      l.record_asset @asset

      redirect_to admin_asset_path(@asset)
    end
  end

  def edit
    @asset = Asset.find(params[:id])
  end

  def update
    @asset = Asset.find(params[:id])

    if params[:asset][:borrower_id]
      params[:asset][:status] = "borrowed"
      @asset.borrower = User.find(params[:asset][:borrower_id].to_i)
    else
      params[:asset][:status] = "available"
    end
    @asset.update_attributes(params[:asset])

    redirect_to admin_asset_path(@asset)
  end

  def qrcode
    @assets = {}
    params['label'].keys.each do |i|
      @assets[i] = Asset.find(params[:label][i])
    end

    render template: "assets/qrcode", layout: false
  end

  def borrowed_status
    @asset = Asset.find_by_uuid(params[:uuid])
  end

  def borrow
    AssetLog.logging_action_for current_user, params[:action] do |l|
      @asset = Asset.find(params[:id])
      l.record_asset @asset

      @asset.borrow_for(current_user)

      redirect_to admin_asset_path @asset
    end
  end

  def return
    AssetLog.logging_action_for current_user, params[:action] do |l|
      @asset = Asset.find(params[:id])
      l.record_asset @asset

      @asset.return

      redirect_to admin_asset_path @asset
    end
  end

  def set_qrcode
    url = view_context.borrow_asset_url(@asset)
    @qr = RQRCode::QRCode.new(url)
  end
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @assets = Asset.where("shared_resource = true")
  end

  def show
    @asset = Asset.find(params[:id])
    @asset_logs = AssetLog.fetch_all_for_asset(@asset)

    set_qrcode
  end

  def new
    @asset = Asset.new
  end

  def create
    AssetLog.logging_action_for current_user, params[:action] do |l|
      @asset = Asset.create(params[:asset])
      l.record_asset @asset

      redirect_to asset_path(@asset)
    end
  end

  def edit
    @asset = Asset.find(params[:id])
  end

  def update
    @asset = Asset.find(params[:id])

    @asset.update_attributes(params[:asset])

    redirect_to asset_path(@asset)
  end

  def qrcode
    @assets = {}
    params['label'].keys.each do |i|
      @assets[i] = Asset.find(params[:label][i])
    end

    render template: "assets/qrcode", layout: false
  end

  def borrowed_status
    @asset = Asset.find_by_uuid(params[:uuid])
  end

  def borrow
    AssetLog.logging_action_for current_user, params[:action] do |l|
      @asset = Asset.find(params[:id])
      l.record_asset @asset

      @asset.borrow_for(current_user)

      BorrowedAssetNotifier.notify_borrowed_asset(current_user, @asset).deliver
      
      redirect_to asset_path @asset
    end
  end

  def return
    AssetLog.logging_action_for current_user, params[:action] do |l|
      @asset = Asset.find(params[:id])
      l.record_asset @asset

      @asset.return

      redirect_to asset_path @asset
    end
  end

  def set_qrcode
    url = view_context.borrow_asset_url(@asset)
    @qr = RQRCode::QRCode.new(url)
  end
end

app/helpers/admin/assets_helper.rb
module Admin::AssetsHelper

  def user_choices
    choices = [["--", nil]]
    user_choices = User.all.map {|u| [u.name, u.id]}
    choices + user_choices
  end
end

app/helpers/assets_helper.rb
module AssetsHelper
  def borrow_asset_url(asset)
    short_url([assets_url, asset.uuid, "borrowed_status"].join('/'))
  end
end

app/views/assets/_borrow_or_return.html.erb
<% if asset.available? %>
  <form action="<%= borrow_asset_path(asset) %>" method="POST">
    <input type="submit" value="Borrow" class="a-button marginRight" />

    This asset is currently available to borrow! 
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>"/>
    <br />


  </form>
<% else %>
  <form action="<%= return_asset_path(asset) %>" method="POST">
    <input type="submit" value="Return" class="a-button marginRight" />
    Borrowed by: <%= asset.borrower.try(:name) %>
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>"/>
    <br />
    <br />
  </form>
<% end %>

app/views/assets/_fields.html.erb
<label>Name of Asset:
  <input type="text" name="asset[name]" value="<%= @asset.name %>" />
</label>

<label>
  Description:
  <textarea name="asset[description]" rows="10"><%= @asset.description %></textarea>
</label>

<label>
  Notes:
  <textarea name="asset[notes]" rows="10"><%= @asset.notes %></textarea>
</label>

<label>
  Is shared resource:
  <%= select_tag "asset[shared_resource]", options_for_select([true, false ], @asset.shared_resource) %>
</label>

app/views/assets/_my_assets.html.erb
<div class="large-12 columns">
	<table width="100%">
  <thead>
    <th width="20%">
      Name
    </th>
    <th width="40%">
      Description
    </th>
    <th width="40%">
      Modified
    </th>
  </thead>

  <tbody>
  <% my_shared_assets.each do |asset| %>
    <tr class='asset-row' data-asset-name='<%= asset.name %>'>
      <td>
        <%= link_to asset.name, asset_path(asset) %>
      </td>
      <td>
        <%= asset.description %>
      </td>
      <td>
        <%= asset.updated_at %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/assets/_qrcode.html.erb
<% if asset.present? %>
  
  <% url = borrow_asset_url(asset) %> 
  <% qr = RQRCode::QRCode.new(url) %>

  <table>
    <tr>
      <td width='150px'>
        <div class="qrcode">
          <table>
          <% qr.modules.each_index do |x| %>
            <tr>  
            <% qr.modules.each_index do |y| %>
             <% if qr.dark?(x,y) %>
              <td class="black"/>
             <% else %>
              <td class="white"/>
             <% end %>
            <% end %>
            </tr>
          <% end %>
          </table>
        </div>
      </td>
      <td style='font-size: 16px; font-family: Arial;'>
        <%= asset.name %>
      </td>
    </tr>
    <tr>
      <td colspan='2', style='font-size: 12px; font-family: Arial;'>
        UUID: <%= asset.uuid %>
      </td>
    </tr>
  </table>
<% end %> 

app/views/assets/borrowed_status.html.erb
<section class="row">
<div class="large-12 columns">

  <h1>Borrow Asset: <%= @asset.name %></h1>


  <span class="label-value">Description:</span>
  <p class="value"><%= @asset.description %></p>

  <span class="label-value">Asset status:</span>
  <p class="value"><%= @asset.status %></p>

<hr>

</div>
</section>

<section class="row">

<div class="large-12 columns">
  <%= render partial: "assets/borrow_or_return", locals: { asset: @asset } %>
</div>
</section>

app/views/assets/edit.html.erb
<section class="row">

<div class="large-12 columns">

  <h1>Edit Asset</h1>

  <%= form_for @asset do %>
  <%= render partial: "fields" %>

  <input type="submit" value="Update Asset" class="a-button" />
<% end %>

</div>

</section>

app/views/assets/index.html.erb
<% content_for :styles do %>
<%= stylesheet_link_tag "crud" %>
<% end %>


<section class="row">
<div class="large-12 columns">
  <h1>Find Assets</h1>
	<table width="100%">
    
  <thead>
    <th width="25%">
      Name
    </th>
    <th width="35%">
      Description
    </th>
    <th width="15%">
      Status
    </th>
    <th width="25%">
      Modified
    </th>
  </thead>

  <tbody>
  <% @assets.each do |asset| %>
    <tr class='asset-row' data-asset-name='<%= asset.name %>'>
      <td>
        <%= link_to asset.name, asset_path(asset) %>
      </td>
      <td>
        <%= asset.description %>
      </td>
      <td>
        <%= asset.status %>
      </td>
      <td>
        <%= asset.updated_at %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

</div>
</section>

<div id="printTagModal" class="reveal-modal large">
  <h2>Print Options</h2>
  <p class="lead">Select the areas on the sheet on which to print the labels.</p>

  <div class="gridster" style="width: 500px; height: 500px;">
    <ul>
      <li data-row="1" data-col="1" data-sizex="2" data-sizey="1" class="asset-tag-1"></li>
      <li data-row="2" data-col="1" data-sizex="2" data-sizey="1" class="asset-tag-3"></li>
      <li data-row="3" data-col="1" data-sizex="2" data-sizey="1" class="asset-tag-5"></li>
      <li data-row="4" data-col="1" data-sizex="2" data-sizey="1" class="asset-tag-7"></li>
      <li data-row="5" data-col="1" data-sizex="2" data-sizey="1" class="asset-tag-8"></li>

      <li data-row="1" data-col="2" data-sizex="2" data-sizey="1" class="asset-tag-2"></li>
      <li data-row="2" data-col="2" data-sizex="2" data-sizey="1" class="asset-tag-4"></li>
      <li data-row="3" data-col="2" data-sizex="2" data-sizey="1" class="asset-tag-6"></li>
      <li data-row="4" data-col="2" data-sizex="2" data-sizey="1" class="asset-tag-8"></li>
      <li data-row="5" data-col="2" data-sizex="2" data-sizey="1" class="asset-tag-10"></li>
    </ul>
  </div>

  <a href="#" class="button print-tags">
    Print
  </a>

  <a class="close-reveal-modal">&#215;</a>
</div>

<%= stylesheet_link_tag 'jquery.gridster' %>

app/views/assets/new.html.erb
<section class="row">
<div class="large-12 columns">

    <h1>Create New Asset</h1>

    <%= form_for @asset do %>
    <%= render partial: "fields" %>

    <input type="submit" value="Create Asset" class="a-button" />
    <% end %>

</div>
</section>

app/views/assets/qrcode.html.erb
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

  <head>
    <meta name=Title content="">
    <meta name=Keywords content="">
    <meta http-equiv=Content-Type content="text/html; charset=macintosh">
    <meta name=ProgId content=Word.Document>
    <meta name=Generator content="Microsoft Word 2008">
    <meta name=Originator content="Microsoft Word 2008">
    <link rel=File-List href="label-template_files/filelist.xml">
    <!--[if gte mso 9]><xml>
     <o:DocumentProperties>
      <o:Author>Jimi Hendrix</o:Author>
      <o:Template>Normal.dotm</o:Template>
      <o:LastAuthor>Jimi Hendrix</o:LastAuthor>
      <o:Revision>1</o:Revision>
      <o:TotalTime>0</o:TotalTime>
      <o:Created>2013-07-19T14:36:00Z</o:Created>
      <o:LastSaved>2013-07-19T14:36:00Z</o:LastSaved>
      <o:Pages>1</o:Pages>
      <o:Lines>1</o:Lines>
      <o:Paragraphs>1</o:Paragraphs>
      <o:Version>12.0</o:Version>
     </o:DocumentProperties>
     <o:OfficeDocumentSettings>
      <o:AllowPNG/>
     </o:OfficeDocumentSettings>
    </xml><![endif]--><!--[if gte mso 9]><xml>
     <w:WordDocument>
      <w:SpellingState>Clean</w:SpellingState>
      <w:GrammarState>Clean</w:GrammarState>
      <w:TrackMoves>false</w:TrackMoves>
      <w:TrackFormatting/>
      <w:PunctuationKerning/>
      <w:DrawingGridHorizontalSpacing>18 pt</w:DrawingGridHorizontalSpacing>
      <w:DrawingGridVerticalSpacing>18 pt</w:DrawingGridVerticalSpacing>
      <w:DisplayHorizontalDrawingGridEvery>0</w:DisplayHorizontalDrawingGridEvery>
      <w:DisplayVerticalDrawingGridEvery>0</w:DisplayVerticalDrawingGridEvery>
      <w:ValidateAgainstSchemas/>
      <w:SaveIfXMLInvalid>false</w:SaveIfXMLInvalid>
      <w:IgnoreMixedContent>false</w:IgnoreMixedContent>
      <w:AlwaysShowPlaceholderText>false</w:AlwaysShowPlaceholderText>
      <w:Compatibility>
       <w:BreakWrappedTables/>
       <w:DontGrowAutofit/>
       <w:DontAutofitConstrainedTables/>
       <w:DontVertAlignInTxbx/>
      </w:Compatibility>
     </w:WordDocument>
    </xml><![endif]--><!--[if gte mso 9]><xml>
     <w:LatentStyles DefLockedState="false" LatentStyleCount="276">
     </w:LatentStyles>
    </xml><![endif]-->
    <style>
    <!--
     /* Font Definitions */
    @font-face
      {font-family:Calibri;
      panose-1:2 15 5 2 2 2 4 3 2 4;
      mso-font-charset:0;
      mso-generic-font-family:auto;
      mso-font-pitch:variable;
      mso-font-signature:3 0 0 0 1 0;}
     /* Style Definitions */
    p.MsoNormal, li.MsoNormal, div.MsoNormal
      {mso-style-parent:"";
      margin:0cm;
      margin-bottom:.0001pt;
      line-height:115%;
      mso-pagination:widow-orphan;
      font-size:8.0pt;
      font-family:"Times New Roman";
      mso-ascii-font-family:Calibri;
      mso-fareast-font-family:"Times New Roman";
      mso-hansi-font-family:Calibri;
      mso-bidi-font-family:"Times New Roman";}
    @page Section1
      {size:612.0pt 792.0pt;
      margin:72.0pt 90.0pt 72.0pt 90.0pt;
      mso-header-margin:35.4pt;
      mso-footer-margin:35.4pt;
      mso-paper-source:0;}
    div.Section1
      {page:Section1;}


    .qrcode {
    }

    .qrcode table {
      border-width: 0;
      border-style: none;
      border-color: #0000ff;
      border-collapse: collapse;
    }
    .qrcode table td {
      border-width: 0; 
      border-style: none;
      border-color: #0000ff; 
      border-collapse: collapse; 
      padding: 0; 
      margin: 0; 
      width: 4px; 
      height: 4px; 
    }
    .qrcode table td.black { background-color: #000; }
    .qrcode table td.white { background-color: #fff; }
    -->
    </style>
    <!--[if gte mso 10]>
    <style>
     /* Style Definitions */
    table.MsoNormalTable
      {mso-style-name:"Table Normal";
      mso-tstyle-rowband-size:0;
      mso-tstyle-colband-size:0;
      mso-style-noshow:yes;
      mso-style-parent:"";
      mso-padding-alt:0cm 5.4pt 0cm 5.4pt;
      mso-para-margin:0cm;
      mso-para-margin-bottom:.0001pt;
      mso-pagination:widow-orphan;
      font-size:12.0pt;
      font-family:"Times New Roman";
      mso-ascii-font-family:Cambria;
      mso-ascii-theme-font:minor-latin;
      mso-hansi-font-family:Cambria;
      mso-hansi-theme-font:minor-latin;}
    </style>
    <![endif]-->
  </head>

  <body bgcolor=white lang=EN-US style='tab-interval:36.0pt'>
    <div class=Section1 style='page-break-after: avoid'>
      <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0
       style='border-collapse:collapse;mso-table-layout-alt:fixed;mso-padding-alt:
       0cm 5.75pt 0cm 5.75pt'>
       <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes;height:144.0pt'>
        <td width=288 style='width:288.0pt;padding:0cm 5.75pt 0cm 5.75pt;height:144.0pt'>
        <p class=MsoNormal>
          <o:p>
            <!--Label 1 -->
            <%= render partial: 'qrcode', locals: {qr: @qr, asset: @assets['1']} -%>
          </o:p>
        </p>
        </td>
        <td width=14 rowspan=5 valign=top style='width:13.5pt;border-top:solid white 1.0pt;
        border-left:none;border-bottom:solid white 1.0pt;border-right:none;
        padding:0cm 0cm 0cm 0cm;height:144.0pt'>
        <p class=MsoNormal><o:p>&nbsp;</o:p></p>
        </td>
        <td width=288 style='width:288.0pt;padding:0cm 5.75pt 0cm 5.75pt;height:144.0pt'>
        <p class=MsoNormal>
          <o:p>
            <!--Label 2 -->
            <%= render partial: 'qrcode', locals: {qr: @qr, asset: @assets['2']} -%>
          </o:p>
        </p>
        </td>
       </tr>
       <tr style='mso-yfti-irow:1;height:144.0pt'>
        <td width=288 style='width:288.0pt;padding:0cm 5.75pt 0cm 5.75pt;height:144.0pt'>
        <p class=MsoNormal>
          <o:p>
            <!--Label 3 -->
            <%= render partial: 'qrcode', locals: {qr: @qr, asset: @assets['3']} -%>
          </o:p>
        </p>
        </td>
        <td width=288 style='width:288.0pt;padding:0cm 5.75pt 0cm 5.75pt;height:144.0pt'>
        <p class=MsoNormal>
          <o:p>
            <!--Label 4 -->
            <%= render partial: 'qrcode', locals: {qr: @qr, asset: @assets['4']} -%>
          </o:p>
        </p>
        </td>
       </tr>
       <tr style='mso-yfti-irow:2;height:144.0pt'>
        <td width=288 style='width:288.0pt;padding:0cm 5.75pt 0cm 5.75pt;height:144.0pt'>
        <p class=MsoNormal>
          <o:p>
            <!--Label 5 -->
            <%= render partial: 'qrcode', locals: {qr: @qr, asset: @assets['5']} -%>
          </o:p>
        </p>
        </td>
        <td width=288 style='width:288.0pt;padding:0cm 5.75pt 0cm 5.75pt;height:144.0pt'>
        <p class=MsoNormal>
          <o:p>
            <!--Label 6 -->
            <%= render partial: 'qrcode', locals: {qr: @qr, asset: @assets['6']} -%>
          </o:p>
        </p>
        </td>
       </tr>
       <tr style='mso-yfti-irow:3;height:144.0pt'>
        <td width=288 style='width:288.0pt;padding:0cm 5.75pt 0cm 5.75pt;height:144.0pt'>
        <p class=MsoNormal>
          <o:p>
            <!--Label 5 -->
            <%= render partial: 'qrcode', locals: {qr: @qr, asset: @assets['7']} -%>
          </o:p>
        </p>
        </td>
        <td width=288 style='width:288.0pt;padding:0cm 5.75pt 0cm 5.75pt;height:144.0pt'>
        <p class=MsoNormal>
          <o:p>
            <!--Label 6 -->
            <%= render partial: 'qrcode', locals: {qr: @qr, asset: @assets['8']} -%>
          </o:p>
        </p>
        </td>
       </tr>
       <tr style='mso-yfti-irow:4;mso-yfti-lastrow:yes;height:144.0pt'>
        <td width=288 style='width:288.0pt;padding:0cm 5.75pt 0cm 5.75pt;height:144.0pt'>
        <p class=MsoNormal>
          <o:p>
            <!--Label 7 -->
            <%= render partial: 'qrcode', locals: {qr: @qr, asset: @assets['9']} -%>
          </o:p>
        </p>
        </td>
        <td width=288 style='width:288.0pt;padding:0cm 5.75pt 0cm 5.75pt;height:144.0pt'>
        <p class=MsoNormal>
          <o:p>
            <!--Label 8 -->
            <%= render partial: 'qrcode', locals: {qr: @qr, asset: @assets['10']} -%>
          </o:p>
        </p>
        </td>
       </tr>
      </table>
    </div>
  </body>
</html>

app/views/assets/show.html.erb
<% content_for :styles do %>
<%= stylesheet_link_tag "crud" %>
<% end %>


<section class="row">

<div class="large-12 colums">

<h1><%= @asset.name %></h1>



<div class="row">
<section class="large-6 columns assetInfo">

  <% if @asset.borrower == current_user %>
    <form action="<%= return_asset_path(@asset) %>" method="POST">
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>"/>
      <input type="submit" value="Return!" class="a-button" />
    </form>
    <span class="label-value">Status:</span>
    <p class="value">Borrowed by you</p>
  <% elsif @asset.available? %>
    <form action="<%= borrow_asset_path(@asset) %>" method="POST">
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>"/>
    <input type="submit" value="Borrow!" class="a-button" />
    <span class="label-value">Status:</span>  
    <p class="value">Available</p>
    </form>
  <% else %>
    <p class="value">Borrowed by <%= @asset.borrower.name %></p>
  <% end %>

  <span class="label-value">Description:</span>
  <p class="value"><%= @asset.description %></p>

  <span class="label-value">Notes:</span>
  <p class="value"><%= @asset.notes %></p>

  <span class="label-value">UUID:</span>
  <p class="value"><%= @asset.uuid %></p>
  
  <a href="#" class="a-button marginRight" data-reveal-id="printTagModal">
    Print QR Code Tag
  </a> 

  <%= link_to "Edit", edit_asset_path(@asset), :class =>"a-button" %>

</section>


<section class="large-6 columns paperTrail">
  <div class="paperTrail-title">
    <h2>Asset History</h2>
  </div>
  <div class="paperTrail-content">
    <%= render partial: "asset_logs/asset_logs_list", locals: { asset_logs: @asset_logs } %>
  </div>
</section>

</div>



</div>

</section>

<div id="printTagModal" class="reveal-modal medium">
  <h2>Print Options</h2>
  <p class="lead">Select the area on the sheet on which to print the label.</p>
  
  <table>
    <tr>
      <td width="80">
        <%= link_to "Label 1", qrcode_asset_path(@asset, format: 'pdf', 'label[1]' => @asset.id), target: '_blank' %>
      </td>
      <td width="80">
        <%= link_to "Label 2", qrcode_asset_path(@asset, format: 'pdf', 'label[2]' => @asset.id), target: '_blank'  %>
      </td>
    </tr>
    <tr>
      <td>
        <%= link_to "Label 3", qrcode_asset_path(@asset, format: 'pdf', 'label[3]' => @asset.id), target: '_blank'  %>
      </td>
      <td>
        <%= link_to "Label 4", qrcode_asset_path(@asset, format: 'pdf', 'label[4]' => @asset.id), target: '_blank'  %>
      </td>
    </tr>
    <tr>
      <td>
        <%= link_to "Label 5", qrcode_asset_path(@asset, format: 'pdf', 'label[5]' => @asset.id), target: '_blank'  %>
      </td>
      <td>
        <%= link_to "Label 6", qrcode_asset_path(@asset, format: 'pdf', 'label[6]' => @asset.id), target: '_blank'  %>
      </td>
    </tr>
    <tr>
      <td>
        <%= link_to "Label 7", qrcode_asset_path(@asset, format: 'pdf', 'label[7]' => @asset.id), target: '_blank'  %>
      </td>
      <td>
        <%= link_to "Label 8", qrcode_asset_path(@asset, format: 'pdf', 'label[8]' => @asset.id), target: '_blank'  %>
      </td>
    </tr>
    <tr>
      <td>
        <%= link_to "Label 9", qrcode_asset_path(@asset, format: 'pdf', 'label[9]' => @asset.id), target: '_blank'  %>
      </td>
      <td>
        <%= link_to "Label 10", qrcode_asset_path(@asset, format: 'pdf', 'label[10]' => @asset.id), target: '_blank'  %>
      </td>
    </tr>
  </table>
  <a class="close-reveal-modal">&#215;</a>
</div>